### ISSUE TITLE
Reload object by same path failed

### ISSUE THREAD

**Issue by omgbebebe** [fbsamples/ghc-hotswap#3]
When I try to reload shared object by same path as an old one, I got error:
```
$ cabal run /tmp/1.so
...normal app output...
Next SO to use: /tmp/1.so
ghc-hotswap-demo: ^^ Could not load 'hs_soHandles', dependency unresolved. See top entry above.
```
I think that the reason is unloading old object after loading a new object. I've made a PR #2 for fix this issue. It works but I don't know maybe it may broke some internal logic or so.  I'm not a real haskeller.:)

**Comment by JonCoens** [comment]
I believe this behavior comes from the GHC linker. It assumes that a file name uniquely identifies a shared object independent of versioning (think libcpp or libregex). To get around this for the hotswapping, each shared object name must be unique (perhaps appending a version number).

Thanks for raising this, I should make it more explicit in the documentation

**Comment by omgbebebe** [comment]
Thank for quick answer!
What do you think about my dirty patch? Can it work or it will cause any kind of race condition?

**Comment by JonCoens** [comment]
I commented on the pull request. It has some collateral damage that would be deal breakers for our use-case.

**Comment by omgbebebe** [comment]
Thank you! It's definitely better to use different object names.:)
