### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by gbaz** [fbsamples/ghc-hotswap#6]
Is there a reason the core hotswap stuff here hasn't had a hackage release? I get it's semi-demo code, but it seems to be the only open-source code around to do stuff these days, and it would be nice if the `GHC.Hotswap` library was directly cabal-installable.

**Comment by xich** [comment]
I'm not sure. @JonCoens is traveling for a few weeks, but will likely have a better answer than this when he gets back. :-)

**Comment by simonmar** [comment]
Released `ghc-hotswap-0.1.0.0` here: https://hackage.haskell.org/package/ghc-hotswap-0.1.0.0
